### PR TITLE
Fix players showing as online after server downtime

### LINKED ISSUE #73: Players are shown as online if they disconnect during downtime
Potential cause of ynoproject/forest-orb#656.

Reproduction steps:
1. connect with client 1
2. connect with client 2 (friend of client 1)
3. `^C` the server
4. close the tab with client 2
5. start the server

Expected behavior: client 2 is shown as offline
Actual behavior: client 2 keeps being shown as online until they connect and disconnect while the server is up

A potential imperfect solution is to set every player with last activity in the given game as offline when the server for that game shuts down (to avoid showing them as online in other games during the downtime) and starts (to clean up after unclean shutdowns), but this still leaves a potential slim gap in which they'd show up as online when the server goes down in some unhandleable manner like a SIGKILL or something similar.

### PR DESCRIPTION
**Pull request by zebraed**
### Description
Sets all players offline when the server starts to clean up stale online status from players who disconnected during server downtime

### Changes
Added `setActivePlayersOffline()` and made it execute when the server starts
players who closed their client while the server was down are correctly shown as offline after the server restarts

The queries to DB were based on the provided ynodb-schema.sql
please check that there are no problem with the queries

Fixes #73 , ynoproject/forest-orb#656

### CODE REVIEW

File: server/database.go [hunk 1]
```diff
@@ -422,6 +422,15 @@ func updatePlayerActivity() error {
 	return nil
 }
 
+func setActivePlayersOffline(game string) error {
+	_, err := db.Exec("UPDATE playerGameData SET online = 0 WHERE game = ? AND online = 1", game)
```
Comment (patapancakes) [inline server/database.go]: Would it be faster to omit `AND online = 1`?

File: server/server.go [hunk 2]
```diff
@@ -75,6 +75,10 @@ func Start() {
 	db = getDatabaseConn(config.dbUser, config.dbPass, config.dbAddr, config.dbName)
 	db.SetConnMaxIdleTime(1 * time.Minute)
 
+	if err := setActivePlayersOffline(config.gameName); err != nil { // clean up players when server starts
```
Comment (patapancakes) [inline server/server.go]:
```
err := ...
if err != nil { ...
```
The rest of the codebase uses this pattern for error checking, please use it.

File: server/server.go [hunk 3]
```diff
@@ -75,6 +75,10 @@ func Start() {
...
+		log.Println("Failed to set active players offline:", err)
```
Comment (patapancakes) [inline server/server.go]: Also consistency related, use `log.Printf("failed to set active players offline: %s", err)` here.
